kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: toi-kafkamanager
  namespace: toi
  labels:
    team: toi
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2025.03.27-09.51-fae135c
  port: 8080
  webproxy: true
  ingresses:
    - https://toi-kafkamanager.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1 # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: '1'
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: nav.no
      claims:
        groups:
          - id: 257b88a4-a7e1-404b-af0a-16934a9f1612
  kafka:
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [
            {
              "name": "toi.rapid-1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "toi.rekrutteringsbistand-stilling-1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "AVRO"
            },
            {
              "name": "toi.kandidat-3",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "toi.sammenstilt-kandidat",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "toi.tillretteleggingsbehov-1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "dir-stilling-ekstern-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
